config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root to: "products#index"

  get '/products', to: 'products#index'

  get '/products/new', to: 'products#new'
  
  post '/products', to: 'products#create'

  get '/product/:id', to: 'products#show'

  get '/products/:id/edit', to: 'products#edit'

  patch '/product/:id', to: 'products#update'
  put '/product/:id', to: 'products#update'

  delete '/product/:id', to: 'products#delete'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all
	end

	def show
			@product = Product.find(params[:id])
	end


	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to products_path
		else
			render :new
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to products_path
		else
			render :edit 
		end
	end

	def destroy 
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end



	private

		def product_params
			params.require(:product).permit(:name, :description, :price)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Papeleria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <header>
      <h1>La Papeleria</h1>
      
      <div class="user-area">
        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </p>
      </header>
</div>


    <%= yield %>
 
  </body>
</html>

app/views/products/edit.html.erb
<h2> Editar Nuevo Producto </h2>

<%= form_for @product do |f| %>

	<div>
		<%= f.label :name %>	
		<%= f.text_field :name %>	
	</div>

	<div>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>

	<div>
		<%= f.label :price %>
		<%= f.number_field :price %>
	</div>

	<div>
		
		<%= f.submit "Guardarlo" %>

	</div>

	<% end %>

app/views/products/index.html.erb
<h2> Productos </h2>
<hr>
<a class="btn btn-primary" href="/products/new" role="button">Agregar producto</a>
<hr>
<table>

	<tr>
		<thead>
			<th>Nombre</th>
			<th>Descripcion</th>
			<th>Precio</th>
		</thead>
	</tr>

<% @products.each do |producto| %>
	<tr>
		<td><%= link_to producto.name, product_path(producto) %> </td>
		<td><%= producto.description %> </td>
		<td><%= producto.price %> </td>
		
		<td>
			<% if user_signed_in? %>
				<%= link_to "Editar", edit_product_path(producto) %>
				<%= link_to "Eliminar", producto, method: :delete, data: { confirm: "Seguro que quieres borrar?"} %>
			<% end %>

		</td>
	</tr>
<% end %>

</table>

app/views/products/new.html.erb
<h2> Agregar Nuevo Producto </h2>

<%= form_for @product do |f| %>

	<div>
		<%= f.label :name %>	
		<%= f.text_field :name %>	
	</div>

	<div>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>

	<div>
		<%= f.label :price %>
		<%= f.number_field :price %>
	</div>

	<div>
		
		<%= f.submit %>

	</div>

	<% end %>

app/views/products/show.html.erb
<h3> <%= @product.name %> </h3>
<p> <%= @product.description %> </p>
<p>$ <%= @product.price %> </p>

<%= link_to "<volver", :back %>